// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CharacterCountController from "./character_count_controller"
application.register("character-count", CharacterCountController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ProgressController from "./progress_controller"
application.register("progress", ProgressController)
